version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 3000:3000
            - 9000:9000
        depends_on:
            - postgres
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    postgres:
        container_name: postgres_api_dev
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: bangsa-api
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports: 
            - 5434:5432
        volumes:
            - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  docker-nest-postgres: